name: CommunityBridge
version: 2.3.7.454
description: Community Bridging plugin based off of ChillerCrafts ForumBridge plugin
authors: [Feaelin, NoRC, ChillerCraft]
website: http://dev.bukkit.org/server-mods/communitybridge-fm/

softdepend: [bPermissions, GroupManager, PermissionsBukkit, PermissionsEx, Vault, zPermissions]
main: org.communitybridge.main.CommunityBridge

commands:
  cbreload:
    description: Reloads CommunityBridge's configuration from disk.
    permission: communitybridge.cbreload
    permission-message: "§cYou do not have access to that command."
  cbsync:
    description: Synchronizes yourself.
    permission: communitybridge.cbsync
    permission-message: "§cYou do not have access to that command."
  cbsynctarget:
    description: Synchronizes the specified player.
    permission: communitybridge.cbsync
    permission-message: "§cYou do not have access to that command."
  cbsyncall:
    description: Synchronizes all players.
    permission: communitybridge.cbsyncall
    permission-message: "§cYou do not have access to that command."

permissions:
  communitybridge.*:
    description: Grants access to all CommunityBridge commands
    children:
      communitybridge.cbrank: true
      communitybridge.cbreload: true
      communitybridge.cbsync: true
      communitybridge.cbsynctarget: true
      communitybridge.cbsyncall: true
  communitybridge.cbrank:
    description: Allows use of the /cbrank command.
    default: op
  communitybridge.cbreload:
    description: Allows use of the /cbreload command.
    default: op
  communitybridge.cbsync:
    description: Allows use of the /cbsync command.
    default: true
  communitybridge.cbsynctarget:
    description: Allows use of the /cbsync <player> command.
    default: op
  communitybridge.cbsyncall:
    description: Allows use of the /cbsyncall command.
    default: op
